apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gkicgo36e-nodejs 
  janus-idp.io/tekton: gkicgo36e-nodejs
  backstage.io/kubernetes-id: gkicgo36e-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gkicgo36e-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml