apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gkicgo36e-nodejs-gitops
  description: This is GitOps manifest for gkicgo36e-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=gkicgo36e-nodejs
    backstage.io/kubernetes-id: gkicgo36e-nodejs 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: sjm-rhtap/gkicgo36e-nodejs-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gkicgo36e-nodejs
